[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "mixed-case-variable"]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
robinhood_testnet = "${ROBINHOOD_TESTNET_RPC_URL}"
